apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.labels.app_name }}
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.labels.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app_name }}
    spec:
      containers:
      - image: nginx
        name: nginx
