apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.labels.app_name }}
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
